.gitignore
.vscode/settings.json

I saw that .vscode was in the root structure of the project. I thought this was odd because to my knowledge, the .vscode folder is meant to store the settings for the User and Workplace environments. Also a bit worried that the folder would somehow end up on live. Therefore, I have done these two things.
- Removed `.vscode/` from repository
- Added `.vscode/` to `.gitignore`
Hope these small changes can help you out!

Removed vscode folder

---

.github/CODESTYLE.md
.github/CONTRIBUTING.md
.gitignore

When I was committing changes to my fork, I realized that there was a drastic difference between how I write my commit messages compared to yours. As a result I tried rebasing those messages and well...
After that little incident, I realized that it might be beneficial to have a `CODESTYLE.md` file, not just for me, but possibly for other contributors as your project grows. I tried my best to replicate your preferences in this document, but there might be things that I am missing or concepts that I am not aware of. So feel free to edit/request changes to your liking!
> [!CAUTION]
> I accidentally committed `add build instructions`, this was meant for another branch. Due to lack of knowledge, I just removed it from this commit. There are also two merges present, I don't think they should …

Added CODESYTLE.md

---

poetry.lock
pyproject.toml
src/thread/thread.py
src/thread/utils/__init__.py
src/thread/utils/algorithm.py
tests/test_parallelprocessing.py

- Removed numpy for pure python inplementation
- Closes #24 

Removing numpy

---

poetry.lock
pyproject.toml
src/thread/__init__.py
src/thread/_types.py
src/thread/decorators.py
src/thread/exceptions.py
src/thread/thread.py
tests/test_decorator.py

Added decorators such that functions can be decorated and automatically ran in threads on invocation
- Closes #28 
- Closes #29 
- Closes #30

Added decorators

---

src/thread/_types.py
src/thread/decorators.py
src/thread/thread.py
tests/test_decorator.py

Made the use of threaded decorators type-safe by overriding the original function's signature with ParamSpec and TypeVar.
- Closes #32 
```py
import thread
@thread.threaded
def a(x: int):
return 2 + x
a1 = a(3)
a2 = a1.result
a3 = a1.get_return_value()
@thread.threaded()
def b(x: int):
return 2 + x
b1 = b(3)
b2 = b1.result
b3 = b1.get_return_value()
@thread.threaded()
def c(x: int):
return 2 + x
c1 = c(3)
c2 = c1.result
c3 = c1.get_return_value()
```
#

Threaded Decorator Type-Safety

---

src/thread/_types.py
src/thread/thread.py

Update Parallel Processing's `function` argument signature to accept multiple keyword arguments
- Related Issue #42

Fix: parallel processing func signature

---

.github/CODE_OF_CONDUCT.md
src/thread/__init__.py
src/thread/_types.py
src/thread/decorators/_processor.py
src/thread/decorators/_threaded.py
src/thread/exceptions.py
src/thread/thread.py

- Update documentation links to `/docs/v1.0.0`
- Update contact email

Chore: update links and email

---

src/thread/thread.py
src/thread/utils/algorithm.py
tests/test_algorithm.py

- Improves memory efficiency
- Improves runtime
- Closes #45 

Perf: memory optimisation for ParallelProcessing

---

.github/workflows/release.yml

Update CI to publish on release instead of tag creation.
This is so that I can sign the tags 😅 

ci: Trigger on release instead of tag

---

src/thread/thread.py

- Reworking how thread killing is implemented
- Improving runtime performance
- Closes #52

Improving thread performance

---

.github/workflows/test-worker.yml
CITATION.cff
tests/__init__.py
tests/test_algorithm.py
tests/test_decorator.py
tests/test_parallelprocessing.py
tests/test_thread.py

The tests directory shouldn't have an `__init.py__` and the imports into your package should just use the package name not `src.packagename`.
See: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code
I've ran the tests locally in a virtualenv to verify it works, and the tests passed locally.

fix tests directory shouldn't have init.py

---

.github/CODESTYLE.md
ruff.toml
src/thread/__init__.py
src/thread/__main__.py
src/thread/_types.py
src/thread/cli.py
src/thread/decorators/_processor.py
src/thread/decorators/_threaded.py
src/thread/exceptions.py
src/thread/thread.py
src/thread/utils/__init__.py
src/thread/utils/algorithm.py
src/thread/utils/config.py
tests/test_algorithm.py
tests/test_decorator.py
tests/test_parallelprocessing.py
tests/test_thread.py

- Conforming to 4 space indents (PEP8)
- Ruff code formatting
- https://github.com/python-thread/thread/discussions/62

Style: Conforming to PEP8

---

src/thread/thread.py
src/thread/utils/__init__.py
src/thread/utils/config.py
tests/test_verbosity.py

Feature: verbosity setting

---

src/thread/thread.py

- Enforce non-empty dataset
- Closes #68 

Fix: enforce nonempty dataset

---

CITATION.cff
README.md
pyproject.toml
src/thread/__init__.py
src/thread/_types.py
src/thread/decorators/_processor.py
src/thread/decorators/_threaded.py
src/thread/exceptions.py
src/thread/thread.py
tests/conftest.py
tests/test_dataframe_compatibility.py
tests/test_thread.py
tests/test_verbosity.py

- Add compatibility options
- Related Issue #67

Feature: dataframe support

---

.github/labeler.yml
.github/settings.yml
.github/workflows/labeler.yml
.github/workflows/linter.yml
.github/workflows/test-worker.yml
ruff.toml
src/thread/thread.py
tests/test_parallelprocessing.py
tests/test_thread.py
tests/test_verbosity.py

- extending ruff configuration
- Adding auto labeler
- Adding linting workflow
- Related Issue #70 

Ci: improving ci

---

CITATION.cff
README.md
pyproject.toml
src/thread/__init__.py
src/thread/_types.py
src/thread/decorators/_processor.py
src/thread/decorators/_threaded.py
src/thread/exceptions.py
src/thread/thread.py

Static typechecking types `_get_value` as a function which expects the arguments `SupportsXXX` and `int` and not a protocol-compatible type.
- Closes #

Fix: Static typechecking behaving weirdly

---

src/thread/utils/algorithm.py
tests/test_algorithm.py

Made chunking return a generator instead of a list
- Closes #

Make chunking more memory efficient

---

poetry.lock
pyproject.toml
ruff.toml
src/thread/__init__.py
src/thread/__version__.py
src/thread/utils/meta.py
src/thread/version.py
tests/library/test_version.py

- Make version resolve with importlib
- This makes it unnecessary to manually update the version number in __init__.py
- Closes #

feat: Resolve version from pip

---

src/thread/utils/config.py

- Cast string type to string literal type
- Closes #

fix: Cast verbosity comparison to Literal type

---

CITATION.cff
pyproject.toml
src/thread/__init__.py

chore(ver): Bump v2.0.1 -> v2.0.2

---

.github/workflows/deploy-docs.yml
docs/src/pages/index.mdx

- Add deploying and staging CI
- Small docs bug fix
- Related Issue #89

ci(depoly): Deploy ci

---

CITATION.cff
docs/src/pages/_meta.json
docs/src/pages/docs/_meta.json
docs/src/pages/docs/index.mdx
docs/src/pages/docs/latest/index.mdx
docs/src/pages/index.mdx
docs/theme.config.tsx
pyproject.toml
src/thread/__init__.py
src/thread/thread.py

- Fix invalid return type with ConcurrentProcessing
- Closes #136

fix: Invalid concurrent-processing return type

---

CITATION.cff
docs/src/pages/_meta.json
docs/src/pages/docs/_meta.json
docs/src/pages/docs/index.mdx
docs/src/pages/docs/latest/index.mdx
docs/src/pages/index.mdx
docs/theme.config.tsx
poetry.lock
pyproject.toml
src/thread/__init__.py
src/thread/utils/meta.py
src/thread/version.py

Compiling python with thread included do not play nice with resolving version with `importlib`.
- Closes #141

fix: Resolve version manually

---

.github/workflows/deploy-docs.yml
.github/workflows/draft-release-tag.yml
.github/workflows/linter.yml
.github/workflows/test-worker.yml

- Check for changed files and only run CI when needed

ci: Only run CI when necessary
